package Practice.Annotation;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.lang.annotation.Annotation;
import java.util.Set;

@SupportedAnnotationTypes("Practice.Annotation.Check")
@SupportedSourceVersion(SourceVersion.RELEASE_21)
public class CheckAnnotationProcessor extends AbstractProcessor {
    private Messager messager;
    private Filer filer;

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        messager = processingEnv.getMessager();
        filer = processingEnv.getFiler();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {

            for (Element element : roundEnv.getElementsAnnotatedWith(Check.class)) {
                String className = element.getSimpleName().toString();

                try {
                    // Create a file in the "resources" directory
                    FileObject fileObject = filer.createResource(
                            StandardLocation.CLASS_OUTPUT,
                            "",
                            className + ".generated.txt"
                    );

                    try (Writer writer = fileObject.openWriter()) {
                        writer.write("This file is generated for class: " + className + "\n");
                        writer.write("Generated by FileCreatingProcessor.\n");
                    }

                    messager.printMessage(Diagnostic.Kind.NOTE, "File created: " + fileObject.toUri());

                } catch (IOException e) {
                    messager.printMessage(Diagnostic.Kind.ERROR, "Failed to create file: " + e.getMessage());
                }
            }

        return true;
    }
}
